services:
  postgres-db:
    build:
      context: ./data-base
      dockerfile: Dockerfile.db
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: conitrack
    restart: always      
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d conitrack"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: DEV
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/conitrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  db_data:
