spring:
  application:
    name: conitrack
  thymeleaf:
    cache: false
  datasource:
    # Uncomment this section to use H2 Database
    # url: jdbc:h2:mem:testdb
    # driverClassName: org.h2.Driver
    # username: sa
    # password:
    # h2:
    #   console:
    #     enabled: true
    url: jdbc:postgresql://conitrack_8afq_user:Y3ZOu3R4QPuXcS4qcDZyIA6Jp3wtFFBj@dpg-d05um8ruibrs739k77p0-a/conitrack_8afq
    username: conitrack_8afq_user
    password: Y3ZOu3R4QPuXcS4qcDZyIA6Jp3wtFFBj
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          charSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
    show-sql: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources
      additional-exclude: static/**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
#  sql:
#    init:
#      mode: always

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    session:
      timeout: 300s

logging:
  level:
    org.springframework.security: DEBUG
    org.thymeleaf.extras.springsecurity6: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.devtools: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG